# -*- coding: utf-8 -*-
"""Operacion.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vmnAK_vAfqBMlZy6WzIJRheub9NVQRrC
"""

# Operación simple
numero1 = 5
numero2 = 10
suma = numero1 + numero2
print("La suma de", numero1, "y", numero2, "es:", suma)
print('1. Cayllagua Mamani Franklin')
print('2. Flores Limachi Iver Josue')
print('3. Limachi Marca Ariel David')
print('4. Mamani Clavijo Omar')



